
spring:
  application:
    name: springboot-rest
  cloud:
    kubernetes:
      loadbalancer:
        mode: SERVICE
logging:
  level:
    com.example.rest: DEBUG
#    org.springframework.boot: DEBUG
